version: '3'
services:

  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
      - "9092:9092"
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
networks:
  AppNet: