version: '3'
services:
  mysqldb:
    image: mysql'
    container_name: mysqldb_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tpachato
    ports:
      - "3306:3306"
  springboot
    image: aymenjerbi/back-project
    container_name: springboot
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tpachato?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
   
    depends_on:
      - mysqldb
      
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
      - "9092:9092"
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
networks:
  AppNet: